### ISSUE TITLE
Add aspect ratio support

### ISSUE THREAD

**Issue by sergystepanov** [giongto35/cloud-game#105]
Added proper nearest neighbour up/downscaling support with aspect ratio calculation.
Now it sets the initial viewport (output image) resolution to the base resolution from the loaded core upscaled by 2 to remove resampling artefacts (as on pictures below). So the manual resolution config for each core now removed completely.
A Sony BIOS intro now is being shown properly.
Need some testing.

Before
![image](https://user-images.githubusercontent.com/846874/66663025-969f3380-ec52-11e9-87bc-9dc72533a722.png)

After
![image](https://user-images.githubusercontent.com/846874/66663085-bb93a680-ec52-11e9-8a64-3e800337d555.png)

**Comment by giongto35** [comment]
Nice.
How you do the upscaling and down scaling. I expect it to be fast so it will not affect streaming performance. I think interpolation scaling might cause it slow. 
Does viewport resolution for GBA is still fixed with 240*160 again?

**Comment by sergystepanov** [comment]
It's just a basic [nearest neighbor algo](http://tech-algorithm.com/articles/nearest-neighbor-image-scaling/) (interpolation), same as yours but it works properly (: And it is fast.

Something like that:
```
func toRgba(fn convert, width int, height int, packedWidth int, data []byte) *image.RGBA {
	xRatio := ((width << 16) / ewidth) + 1
	yRatio := ((height << 16) / eheight) + 1

	for i := 0; i < eheight; i++ {
		for j := 0; j < ewidth; j++ {
			x2 := (j * xRatio) >> 16
			y2 := (i * yRatio) >> 16

			index := (y2 * packedWidth) + x2

			fn(data, index, j, i) 
                        // pixel := (int)(data[index*int(video.bpp)]) + 
                        // ((int)(data[(index*int(video.bpp))+1]) << 8)
		}
	}

	return outputImg
}
```
Viewport resolution is fixed to the basic core resolution * 2 and it ignores the config. Not sure what resolution will be best or how to handle this stuff, double scaling leads to a noticeable performance hit but, on the other hand, texts in games don't look like garbage.
Speaking about performance bottlenecks, you could try to run your profiler to see that the largest one is frame render time in a core, second -- vpx encoding time, third -- these go RGBA.set parts `outputImg.Set(x, y, color.RGBA{byte(r8), byte(g8), byte(b8), 255})`.

**Comment by giongto35** [comment]
ok. I think that scaling algorithm should work in this case. I think it's fast enough.

The legend of Zelda screen is broken because we scaled down the resolution last commit. It was fine with 240*160. The number I got in config is the major resolution collecting from all frames in each emulator. However, that number varies from Game to Game, not emulator. I think we can have a dynamic external config that can be updated per game.

Regarding to performance bottleneck, you are right pointing those three, and all of them are not modifiable :(

Btw, the project is currently using VP8 encoder because I realize the implementation of Go H264 Encoder is not proper.
https://github.com/giongto35/cloud-game/blob/master/pkg/util/util.go#L90

**Comment by sergystepanov** [comment]
> The legend of Zelda screen is broken because we scaled down the resolution last commit. It was fine with 240*160. 

Not sure about that, I will try to run the master branch with 240x160.

> The number I got in config is the major resolution collecting from all frames in each emulator. However, that number varies from Game to Game, not emulator. I think we can have a dynamic external config that can be updated per game.

Ok, if you want a resolution config for each core so be it, in my opinion it's too tedious to hand pick these resolutions and a simple x2 scale works fine. I'll add a new cmd key for scaling factor of resolutions in the config, then.

> Btw, I have both VP8 and H264 encoder in the codebase and experimented them. The project is currently using VP8 encoder because I realize the implementation of Go H264 Encoder is not proper.
https://github.com/giongto35/cloud-game/blob/master/pkg/util/util.go#L90

I'm getting some segfault crash when the first frame is being encoded with x264.

**Comment by sergystepanov** [comment]
@giongto35 maybe it is easier to chat about this stuff in Discord or Telegram (: Do you have any social media accounts? Will be great.

**Comment by giongto35** [comment]
@sergystepanov Yes, I was about asking your social account for easier discussion also. Mine is can you find +6588134649 on telegram?

**Comment by sergystepanov** [comment]
I think it allows searching only in your country of registration, so no. 
Try my direct link https://t.me/exist

**Comment by giongto35** [comment]
I just realized that, I handpicked the resolution just because I didn't have upscaling : D . If we have upscaling algorithm work, we can just fixed the resolution to be 360p: 480 x 360 or 480p ... (configurable).

**Comment by giongto35** [comment]
Not related to this issue, but I updated audio streaming by batch. https://github.com/giongto35/cloud-game/pull/106/files . You can review it.

**Comment by sergystepanov** [comment]
I've just pushed commit into [my fork](https://github.com/sergystepanov/cloud-game/tree/feature/aspect-ratio). Can you make a `dev` branch here I will make PR into that instead of  
the master branch.

You can try how it works with different settings in the config. Couldn't make it work with cmd flags, don't know how to pass them through the whole app into a room and emulator (:
And one more thing with this nearest interpolation -- without x2 resolution scaling there is too much aliasing.

> Not related to this issue, but I updated audio streaming by batch. https://github.com/giongto35/cloud-game/pull/106/files . You can review it.

Seems alright. Not sure what's that all about slice copies but now it's working without crashes. Thanks.

**Comment by giongto35** [comment]
Thank you :D, I will check it later because I will sleep soon
I pushed dev branch, you can send PR to that first :D

**Comment by giongto35** [comment]
@sergystepanov : Tested,
I think Aspect ratio makes more sense, omit hardcoded config. 
Aliasing is the unavoidable problem of nearest neighbor algorithm and even x2 resolution I still see some aliasing. I think applying bilinear scaling can resolve that but it's ok to go forward with nearest neighbor algorithm for now.

**Comment by sergystepanov** [comment]
So, I was thinking to make it use by default your old interpolation algo without xN scaling and to add two new cmd params: --use-aspect-ratio, --scaler (old, nearest, skip), and maybe --out-resolution (NxM = 120x200, 320x240 and so on) but I don't know how to pass them down into the room and emulator modules, is it possible? And what you think?

**Comment by giongto35** [comment]
Let's stick with nearest neighbor all the time. Later if we have bilinear algorithm, we can switch to it.
I think having a flag for --use-aspect-ratio is valid, can make it default as false.

**Comment by sergystepanov** [comment]
Ok, got it. You can tweak those hardcoded params as you see fit (code also) and merge it.
Will try to implement both bilinear and bicubic interpolations later (and next, I guess, going to research proper x264 encoder support and encoding)

**Comment by giongto35** [comment]
To pass the config
https://github.com/sergystepanov/cloud-game/blob/master/pkg/worker/overworker.go#L53
can change to pass cfg to Handler
worker := NewHandler(o.cfg)

and
https://github.com/sergystepanov/cloud-game/blob/master/pkg/worker/handlers.go#L138
can change to pass cfg to Room also
room := room.NewRoom(roomID, gameName, videoEncoderType, h.onlineStorage, h.cfg)

You can leave it to me if you feel like not want to do it and just hardcode config first :D

**Comment by sergystepanov** [comment]
Oh, I see, leave it to me, then. I thought it's harder to do (:.

**Comment by giongto35** [comment]
The x264 encoding framework I based on https://github.com/gen2brain/x264-go
I test on production with x264 and realized it is slower than VP8. You can try switching to config.H264 and profile, I saw they have some hotspot with high allocation in the implementation.

**Comment by sergystepanov** [comment]
> The x264 encoding framework I based on https://github.com/gen2brain/x264-go
I test on production with x264 and realized it is slower than VP8. You can try switching to config.H264 and profile, I saw they have some hotspot with high allocation in the implementation.

Hm, that's strange, I assume, both encode in the software mode without hardware acceleration, with the same settings? then x264 should be faster.
Anyway it crashes on me as I said on the first frame encode call (on Windows).

**Comment by giongto35** [comment]
The slow part is the Golang implementation of the library is flawed, not H264 streaming. I think the creator of Pion (Golang webRTC) recommended to use GStreamer but I haven't tried to use it. =.= 
I think it's better if we research on GStreamer, I think it has better API https://github.com/pion/example-webrtc-applications/tree/master/gstreamer-send . Both VP8 and H264 library I'm using is non-official and relied on CGO.

btw, H264 is working on my machine. :/ hmm maybe another OS issue. I think it will work on ubuntu VM.

**Comment by sergystepanov** [comment]
I decided to use calculated AR from core provided base w and h values (PAR 1:1) because core provided AR in most cases will be wrong. By default, viewport size is set to 320x240 before AR calculations.

**Comment by giongto35** [comment]
Got your point, I will land your change on master after retest and close this ticket. Is it ok ?

**Comment by sergystepanov** [comment]
Sure thing. Also you can remove those hardcoded width and heights for each core from the config unless you need them for something.

**Comment by giongto35** [comment]
I just realize that the images produced by bilinear is a bit blurry and low contrast. I'm experimenting how to deal with it. Maybe I can increase contrast or try increasing resolution. 

> Bilinear interpolation works by interpolating pixel color values, introducing a continuous transition into the output even where the original material has discrete transitions. Although this is desirable for continuous-tone images, this algorithm reduces **contrast** (sharp edges) in a way that may be undesirable for line art. Bicubic interpolation yields substantially better results, with only a small increase in computational complexity.
